name: Deploy to VM2

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 푸시될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted Runner에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 최신 코드를 체크아웃

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Docker 환경 설정
      with:
        driver-opts: image=moby/buildkit:latest
        install: true  # Buildx를 설치

    - name: Build application on VM1
      run: |
        cd ~/msa-project
        docker-compose build  # Docker Compose로 모든 서비스 빌드

    - name: Deploy application to VM2
      env:
        DEPLOY_USER: user1
        DEPLOY_HOST: 192.168.137.11
      run: |
        sshpass -p '1234' ssh $DEPLOY_USER@$DEPLOY_HOST 'bash -s' < ~/msa-project/deploy.sh

