name: Deploy to VM2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted Runner에서 실행

    steps:
    # 1. 최신 코드를 가져오기
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Buildx 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        install: true

    # 3. Docker 레이어 캐시 설정
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # 4. Docker Compose로 서비스 빌드 및 실행
    - name: Build application on VM1
      run: |
        cd /home/user1/msa-project
        docker-compose down
        docker-compose build
        docker-compose up -d

    # 5. 애플리케이션을 VM2로 배포
    - name: Deploy application to VM2
      env:
        DEPLOY_USER: user1  # VM2 사용자 이름
        DEPLOY_HOST: 192.168.137.11  # VM2 IP 주소
      run: |
        sshpass -p '1234' ssh $DEPLOY_USER@$DEPLOY_HOST 'bash -s' < /home/user1/msa-project/deploy.sh

